version: '3.7'

services:
  api:
    image: docker.pkg.github.com/ciffelia/twilens/api
    build:
      context: .
      dockerfile: ./dockerfile/api.dockerfile
      cache_from:
        - docker.pkg.github.com/ciffelia/twilens/api
        - docker.pkg.github.com/ciffelia/twilens/web
    init: true
    environment:
      PORT: 8080
    expose:
      - 8080

  web:
    image: docker.pkg.github.com/ciffelia/twilens/web
    build:
      context: .
      dockerfile: ./dockerfile/web.dockerfile
      cache_from:
        - docker.pkg.github.com/ciffelia/twilens/web
        - docker.pkg.github.com/ciffelia/twilens/api
    init: true
    environment:
      PORT: 3000
      TWILENS_API_BASE_URL: http://api:8080
